server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL_USER:jdbc:mysql://localhost:3306/user_service_db?useSSL=false&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:*****@***}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:MyJwtSecretKey123456itscountisvrylowsoincreaasesomerandomchar}
  expiration: ${JWT_EXPIRATION:3600000}
